spring.application.name=gestorcontratos.registrousuario

spring.profiles.active=postgres

spring.datasource.url=jdbc:postgresql://db.mvtdklxcdxfgrwqhbdwz.supabase.co:5432/postgres?user=postgres&password=supabase123$
spring.datasource.username=postgres
spring.datasource.password=supabase123$
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/db_registro
#spring.datasource.username=postgres
#spring.datasource.password=secretpassword
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.co.com.politecnico.gestorcontratos=DEBUG
logging.level.org.hibernate.SQL=DEBUG
