server:
  port: 8081

app:
  auth:
    allow-test-user-header: false

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gestor_tareas}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

rmi:
  registry-port: 1100
  auth-host: localhost
  auth-port: 1099
